version: '3.8'

services:
  clinica-shiba:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - PORT=8090
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,https://clinica-shiba-angular-theta.vercel.app
    volumes:
      - clinica_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  clinica_data: 