services:
  - type: web
    name: clinica-shiba-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8090
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:4200,https://your-frontend-domain.com
    disk:
      name: clinica-shiba-data
      mountPath: /app/data
      sizeGB: 1 